# Generated by Django 4.0.1 on 2022-01-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useranswers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Варианты', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='useranswers',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
