# Generated by Django 4.0.1 on 2022-01-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answer_options_alter_useranswers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answerssss', to='api.question'),
            preserve_default=False,
        ),
    ]
