# Generated by Django 4.0.1 on 2022-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_question_quiz_remove_useranswers_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerText',
            field=models.CharField(default='as', max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='questionText',
            field=models.CharField(default='asd', max_length=1200),
            preserve_default=False,
        ),
    ]
