# Generated by Django 4.0.1 on 2022-02-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quiz_res1_quiz_res2_quiz_res3_quiz_res4_quiz_res5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='res1',
            field=models.CharField(max_length=255, verbose_name='Ценностно-смысловая организация личности'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='res2',
            field=models.CharField(max_length=255, verbose_name='Организация деятельности'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='res3',
            field=models.CharField(max_length=255, verbose_name='Решительность'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='res4',
            field=models.CharField(max_length=255, verbose_name='Настойчивость'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='res5',
            field=models.CharField(max_length=255, verbose_name='Самообладание'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='res6',
            field=models.CharField(max_length=255, verbose_name='Самостоятельность'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='res7',
            field=models.CharField(max_length=255, verbose_name='Показатель лжи'),
        ),
    ]
