# Generated by Django 4.0.1 on 2022-02-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quiz_code_quiz_is_parent_alter_quiz_res1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='code',
        ),
    ]
